### ISSUE TITLE
Does this support Web android?

### ISSUE THREAD

**Issue by Zopenzop** [xclud/dart_serial#1]
Would this package still work if I am using the web app on an android device?

**Comment by xclud** [comment]
No. None of the browsers in the market support serial port on mobile. More info here: https://developer.mozilla.org/en-US/docs/Web/API/SerialPort

**Comment by Zopenzop** [comment]
I see. Thanks for the information.

**Comment by Zopenzop** [comment]
@xclud I haven't been working with browsers much so just wanted to ask if there are any chances we might see serial port functionality on Android browsers in near future, if you happen to have any info about the same.

**Comment by xclud** [comment]
I don't think this will be possible in the next few years. I didn't hear anything about such a feature for the browsers.

Disclaimer: This is my personal idea.
