### ISSUE TITLE
Displaying QR code

### ISSUE THREAD

**Issue by kumarkrati** [xclud/dart_serial#5]
Hi, I am using 5 inch screen display which is connected to my app. I want to send qr code to this 5 inch display. I am able to send text message.

**Comment by xclud** [comment]
What is the error you are receiving?

**Comment by kumarkrati** [comment]
I am not sure what request to send for it show QR code

**Comment by xclud** [comment]
The device/screen you are working should have documented it. You need you construct the message according to the device manufacturer's specification.

I am closing this issue as it is unrelated to the package. Please feel free to open a new issue any time.
