### ISSUE TITLE
not able to getports list from serial

### ISSUE THREAD

**Issue by siddhamjain02** [xclud/dart_serial#6]
Error: Expected a value of type 'FutureOr<List<SerialPort>>?', but got one of type 'List<dynamic>'
this is the error in lib in web.dart at getports()

var v = await window.navigator.serial.getPorts();

this line in my code led me to error

**Comment by siddhamjain02** [comment]
var v = await window.navigator.serial.getPorts();

**Comment by xclud** [comment]
It works here. I just updated the deps and released a new version. Maybe this helps?

**Comment by siddhamjain02** [comment]
How will I get the updated version

**Comment by siddhamjain02** [comment]
I mean there is no update in pub.dev

**Comment by siddhamjain02** [comment]
Ok got it thanks

**Comment by siddhamjain02** [comment]
![image](https://github.com/xclud/dart_serial/assets/90631127/17aea94f-8ecb-4029-9630-e6b2095aa1be)
not working and the debugger shows error here

**Comment by siddhamjain02** [comment]
@JS('navigator.serial.getPorts')
external Object _getPortList();

Future<dynamic> getPortList() => promiseToFuture(_getPortList());

I had a workaround and this worked in my code by calling the function getPortList()
but it does not work with 
Future<List<SerialPort>>getPortList() => promiseToFuture(_getPortList());
in my code too
so I think casting is having some issue

**Comment by siddhamjain02** [comment]
please ping me if you need something else
